# Generated by Django 5.2.8 on 2026-09-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStPC76lP66TQBd8ed7bBW2U6PQONb1q8Sruccq7zcBUHg2rU7iMMPhJGc&s=10', max_length=500),
        ),
    ]
